### ISSUE TITLE
Please add Cargo.lock

### ISSUE THREAD

**Issue by matthiasbeyer** [santhosh-tekuri/boon#10]
Please add the `Cargo.lock` file to the repository, so this project can be packaged.

**Comment by santhosh-tekuri** [comment]
I some where read:
> You won't include *Cargo.lock* in libraries, but you want to push it for applications. Actually only `cargo new --lib` will add *Cargo.lock* to your *.gitignore*.

**Comment by matthiasbeyer** [comment]
That [changed recently](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html)

Also, you have an example application that I want to package for nixpkgs.
