### ISSUE TITLE
Error message for failed const validation is wrong

### ISSUE THREAD

**Issue by freelon** [santhosh-tekuri/boon#11]
Running the example below gives me an error message of

`- at '': value must be null` 

instead of  

`- at '': value must be "foo"`

 or something similar.
```javascript
// schema.json
{
    "const": "foo"
}
```

```javascript
// invalid.json
"bar"
``` 

Validated with `cargo run --example boon schema.json valid.json` on branch `main`.

**Comment by santhosh-tekuri** [comment]
fixed with af97cee

thanks for reporting the issue

**Comment by santhosh-tekuri** [comment]
try boon 0.5.3 (which includes this fix and dependencies are upgraded)

**Comment by freelon** [comment]
I had already immediately tried it off main after you merged. Thanks for the fast fix!
