### ISSUE TITLE
Add config to disable the default File loader

### ISSUE THREAD

**Issue by theory** [santhosh-tekuri/boon#12]
I'm working on a [postgres extension](/tembo-io/pg-jsonschema) using boon, and I'd like to prevent it from loading the default file loader. Right now I'm replacing it with a no-op loader, but it'd be nice to have a feature to enable to just prevent it from being compiled. Something to complement the `cfg(not(target_arch = "wasm32"))` macro, having the same behavior but not specific to wasm.

**Comment by santhosh-tekuri** [comment]
fixed in da002ca

`Compiler.register_url_loader(...)` is removed. now `Compiler.use_loader(...)` added

FileLoader is now made public.
new struct `SchemeUrlLoader` added which supports previous style url scheme based loaders

see `tests/examples.rs` for changes in usages

**Comment by theory** [comment]
Nice. So if I want it to have no loaders at all, is there something I can pass to `use_loader()` so that `FileLoader` isn't loaded?

**Comment by santhosh-tekuri** [comment]
you can use `SchemeUrlLoader`:

```rust
let loader = SchemeUrlLoader::new();
compiler.useLoader(Box::new(loader));
```
