### ISSUE TITLE
Distribute binaries using Github Releases

### ISSUE THREAD

**Issue by Djiit** [santhosh-tekuri/boon#13]
Hello there,

I'd like to use boon in my CI workflow. Would it be possible for you to add Releases to this repo with binaries generated for common platforms?

Thanks

**Comment by santhosh-tekuri** [comment]
@Djiit 

I think we can do that using https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases

Are you interested in setting up GitHub workflow for this

**Comment by Djiit** [comment]
Yes, I can give it a try

**Comment by Djiit** [comment]
Hello @santhosh-tekuri , any new on this landing on main branch? Thanks

**Comment by santhosh-tekuri** [comment]
merged to main branch

**Comment by Djiit** [comment]
Thank you. Could you push a new tag then?

**Comment by santhosh-tekuri** [comment]
I did just now. but the release workflow is failing

https://github.com/santhosh-tekuri/boon/actions/runs/9300176062/job/25595942659

do you have any idea about this error?

**Comment by Djiit** [comment]
Not sure, I don't know the action the workflow is using. I'll try to have a look

**Comment by santhosh-tekuri** [comment]
release action for target `aarch64-unknown-linux-gnu` is failing. I just commented it to make the release

Action log showing failure: https://github.com/santhosh-tekuri/boon/actions/runs/9300176062

**Comment by Djiit** [comment]
Awesome, thanks!
