### ISSUE TITLE
unable to fetch reference from an URI - `invalid peer certificate: UnknownIssuer`

### ISSUE THREAD

**Issue by etele** [santhosh-tekuri/boon#17]
hi
got an issue while validating a schema

loading a schema:
```
$ boon writer/seqway/request/2-0-6.json 
schema path/to/file/2-0-6.json: failed
error loading https://internal.gitlab.repo/schema/meta/2-0-0: https://internal.gitlab.repo/schema/meta/2-0-0: Connection Failed: tls connection init failed: invalid peer certificate: UnknownIssuer
```

reference in schema:
```
$ cat writer/seqway/request/2-0-6.json 
{
  "$schema": "https://internal.gitlab.repo/schema/meta/2-0-0#",
```

maybe something like
```
SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
```
for defining certificates to use for this

thanks in advance

**Comment by santhosh-tekuri** [comment]
good idea;

I have recently added `-k` flag in 18df725, which will skip cert validation similar to curl. You can try that flag for the time being.

**Comment by etele** [comment]
installed today with `cargo install` i dont see the -k support there
am i missing something?

**Comment by etele** [comment]
ok, build it from sources and now its a bit differenct, seems the -k does not solves it for me

a version command and a `-v` option for verbose run would be a help there too

```
$ ./boon -k writer/seqway/request/2-0-6.json 
schema /writer/seqway/request/2-0-6.json : failed
error loading https://internal.gitlab.repo/schema/meta/2-0-0: https://internal.gitlab.repo/schema/meta/2-0-0: Connection Failed: tls connection init failed: received fatal alert: HandshakeFailure
```

**Comment by santhosh-tekuri** [comment]
@etele I made few changes to fix this in f7b2c6c

could you please retry `-k` flag  from updated sources

**Comment by etele** [comment]
yea, it looks like working now, ty

**Comment by santhosh-tekuri** [comment]
will see how user can provide certs in command line

**Comment by santhosh-tekuri** [comment]
I added `--cacert PEM_FILE` option to cli in d719292

it is similar option in curl. only PEM encoded file is supported. the file can have multiple certs.

could you please very at your end if this flag works fine

**Comment by etele** [comment]
seems working, thanks

```
$ ./boon --cacert /etc/ssl/certs/ca-certificates.crt /path/to/file/2-0-6.json 
schema /path/to/file/2-0-6.json: ok
```

**Comment by santhosh-tekuri** [comment]
great; thanks
