### ISSUE TITLE
async

### ISSUE THREAD

**Issue by AlbanMinassian** [santhosh-tekuri/boon#2]
"boon" is not async. 

Would it be possible to have an async version? Like this example <https://docs.rs/mockito/latest/mockito/#async>.

Thank 

PS: I use `tokio::task::spawn_blocking` as a workaround, but i less "clean"

**Comment by santhosh-tekuri** [comment]
only network I/O the library use is in URLLoader which is pluggable.
the URLLoader needs to use `serde_json::from_reader` which has no async version.
so it doesn't make sense to make boon async

**Comment by AlbanMinassian** [comment]
I say: boon is not asynchronous
You say: boon does not have to be asynchronous 

I respect your point of view (it's your project first).

As a boring axum+tokio+async developer, I think boon can gain popularity if it natively offers to be async.

**Comment by santhosh-tekuri** [comment]
I want to see, how you thought the API would be be example. Only compilation phase needs I/O. The validation phase is purely computational. So having async only effects compilation phase. 

Mostly library users compile schema once and validate many times. So is it worth spending time to support async. Will the async support make this library tied to particular async runtime.

I am new to rust and this is my first project. So I'm no that familiar with async. From my understanding I don't see much benifit.
