### ISSUE TITLE
Installation failure when running on rust image 

### ISSUE THREAD

**Issue by thyageshm** [santhosh-tekuri/boon#20]
Getting the following error across various rust images (versions: 1.77.2, 1.78.0, 1.79.0). I have not tried all the earlier versions. But the observation is that it used to work for those images, and it has started to fail.

Image repo: https://hub.docker.com/_/rust
Dockerfile does:
```
FROM rust:1.79.0
RUN cargo install boon-cli
```

Error:
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/adb10e18-0e0a-4e60-9039-baddac780df4">

**Comment by santhosh-tekuri** [comment]
use `cargo install --path cli --locked`

the readme fixed in d70051e

**Comment by santhosh-tekuri** [comment]
use command `cargo install boon-cli --locked`

you don't need to checkout the repo for this
