### ISSUE TITLE
Meta-Schema validaten fails when files are not referenced with .json

### ISSUE THREAD

**Issue by chdalski** [santhosh-tekuri/boon#21]
Hi,

when creating a meta schema like...:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://json-schema.org/draft/2020-12/schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true
  },
  "allOf" : [
    { "$ref": "meta/core" }
  ],
  // ...
}
```

... the validation fails with `error loading file:///<path_to_schema>/meta/core: No such file or directory (os error 2)` if the file ending is ".json" (for ./meta/core.json), whereas...:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://json-schema.org/draft/2020-12/schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true
  },
  "allOf" : [
    { "$ref": "meta/core.json" } // differs from json-schema
  ],
  // ...
}
```

... works as expected. This behavior differs from the original [json schema](https://github.com/json-schema-org/json-schema-spec/blob/2020-12/schema.json) and should be fixed.

Kind regards.

**Comment by santhosh-tekuri** [comment]
I have tried two compile following schema, and it compiles without any error:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://json-schema.org/draft/2020-12/schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true
  },
  "allOf" : [
    { "$ref": "meta/core" }
  ]
}
```

all schema files from `json-schema.org` are baked into binary, so it should be able to load them from binary;

if you can reproduce the issue from your end, please attach a simple test case to reproduce.

**Comment by chdalski** [comment]
Here is a simple test case:

```shell
dev/projects/boon
at 12:28:16 ➜  boon 2020-12.json
schema 2020-12.json: failed
error loading file:///home/chris/dev/projects/boon/meta/core: No such file or directory (os error 2)
```

[boon.tar.gz](https://github.com/user-attachments/files/16541703/boon.tar.gz)

**Comment by santhosh-tekuri** [comment]
I checked your files. This is not bug. you should use:

```
"$ref": "https://json-schema.org/draft/2020-12/meta/core"
```

instead of:
```
"$ref": "meta/core"
```

see how sample metaschema look like from [here](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/main/remotes/draft2020-12/metaschema-no-validation.json)

in the schema I tested it worked fine because it has `$id` property on top root object, which is used to resolve the relative references.

**Comment by chdalski** [comment]
That's me misunderstanding the documentation, then. Thank you for the explanation.
