### ISSUE TITLE
Dependency idna has patched CVEs

### ISSUE THREAD

**Issue by theory** [santhosh-tekuri/boon#28]
Visible in the [boon dependency report](https://deps.rs/repo/github/Santhosh-tekuri/boon#vulnerabilities):

>rustls: `rustls::ConnectionCommon::complete_io` could fall into an infinite loop based on network input
>
> [RUSTSEC-2024-0336](https://rustsec.org/advisories/RUSTSEC-2024-0336.html)

And:

> idna: `idna` accepts Punycode labels that do not produce any non-ASCII when decoded
>
> [RUSTSEC-2024-0421](https://rustsec.org/advisories/RUSTSEC-2024-0421.html)

**Comment by santhosh-tekuri** [comment]
fixed with 7c420fd0bf99e6d340f8e48a6391435d66470afa
